// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hwibdsbdnluyyencbqxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3aWJkc2Jkbmx1eXllbmNicXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDUzOTUsImV4cCI6MjA1NTIyMTM5NX0.Gxuzk8ece8BeiBCnzcpgxIFUd9nRouwxhuMgHRuwyyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);

// const SUPABASE_URL = "https://qitqsatewwmcjtoavacr.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdHFzYXRld3dtY2p0b2F2YWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDA4NjUsImV4cCI6MjA1MzY3Njg2NX0.aGCy6O_vtqCxwgrrfcYHYregnZx20miVQvFiShwXwlk";
